from __future__ import annotations

PARENT_OP_BRIEF_NORMALIZATION = "brief_normalization"
PARENT_OP_JIRA_PARENT_UPDATE = "jira_parent_update"
PARENT_OP_JIRA_COMMENT_PROJECTION = "jira_comment_projection"
PARENT_OP_DISCORD_FOLLOWUP_PROJECTION = "discord_followup_projection"
PARENT_OP_BACKLOG_PLANNING = "backlog_planning"
PARENT_OP_PM_DECISION_RESOLUTION = "pm_decision_resolution"
PARENT_OP_JIRA_CHILD_FANOUT = "jira_child_fanout"
PARENT_OP_JIRA_CHILD_PROMOTION = "jira_child_promotion"
PARENT_OP_NOTIFICATION_EMIT = "notification_emit"

PARENT_WU_BRIEF_NORMALIZATION_MODEL = "brief_normalization.model"
PARENT_WU_JIRA_PARENT_UPDATE_API = "jira_parent_update.api"
PARENT_WU_BACKLOG_ARCHITECTURE_MODEL = "backlog_planning.architecture_model"
PARENT_WU_BACKLOG_SECURITY_MODEL = "backlog_planning.security_model"
PARENT_WU_BACKLOG_TESTING_MODEL = "backlog_planning.testing_model"
PARENT_WU_BACKLOG_PACKAGE_ASSEMBLY = "backlog_planning.package_assembly"
PARENT_WU_PM_DECISION_MODEL = "pm_decision_resolution.model"
PARENT_WU_JIRA_CHILD_FANOUT_SEED = "jira_child_fanout.seed_issues"
PARENT_WU_JIRA_CHILD_FANOUT_EVALUATE = "jira_child_fanout.evaluate_seed"
PARENT_WU_JIRA_CHILD_FANOUT_ARCHITECTURE_MODEL = "jira_child_fanout.architecture_model"
PARENT_WU_JIRA_CHILD_FANOUT_SECURITY_MODEL = "jira_child_fanout.security_model"
PARENT_WU_JIRA_CHILD_FANOUT_TESTING_MODEL = "jira_child_fanout.testing_model"
PARENT_WU_JIRA_CHILD_FANOUT_PACKAGE_ASSEMBLY = "jira_child_fanout.package_assembly"
PARENT_WU_JIRA_CHILD_PROMOTION_API = "jira_child_promotion.api"
PARENT_WU_JIRA_COMMENT_PROJECTION_API = "jira_comment_projection.api"
PARENT_WU_DISCORD_FOLLOWUP_PROJECTION_API = "discord_followup_projection.api"
PARENT_WU_NOTIFICATION_EMIT = "notification_emit.emit"
