from functools import lru_cache
from typing import Literal

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    database_url: str = "postgresql+psycopg://orchestrator:orchestrator@127.0.0.1:4402/orchestrator"
    allow_sqlite_for_tests: bool = False
    db_pool_size: int = 10
    db_pool_max_overflow: int = 20
    db_pool_timeout_seconds: int = 60
    db_pool_recycle_seconds: int = 1800
    db_pool_pre_ping: bool = True
    log_level: str = "INFO"
    admin_username: str = "admin"
    admin_password: str = "change-me"
    admin_token_secret: str = "local-dev-admin-token-secret"
    admin_token_ttl_seconds: int = 28800
    auth_token_secret: str = "local-dev-auth-token-secret"
    auth_token_ttl_seconds: int = 28800
    discord_oauth_client_id: str = ""
    discord_oauth_client_secret: str = ""
    discord_oauth_redirect_url: str = "http://localhost:4000/api/public/discord/oauth/callback"
    discord_install_state_secret: str = "local-dev-discord-install-secret"
    discord_bot_permissions: int = 3224728621023057
    email_delivery_provider: Literal["smtp", "resend"] = "smtp"
    email_from_name: str = "Master Builder"
    email_from_address: str = "no-reply@masterbuilder.local"
    email_reply_to: str = ""
    smtp_host: str = ""
    smtp_port: int = 1025
    smtp_username: str = ""
    smtp_password: str = ""
    smtp_use_tls: bool = False
    smtp_use_ssl: bool = False
    resend_api_key: str = ""
    cors_origins: str = "http://localhost:4100,http://127.0.0.1:4100"
    cors_origin_regex: str = ""
    admin_ui_base_url: str = "http://localhost:4100"
    jira_action_token_secret: str = "local-dev-jira-action-token-secret"
    github_install_state_secret: str = "local-dev-change-me"
    github_app_slug: str = ""
    public_api_base_url: str = "http://localhost:4000"
    atlassian_oauth_state_secret: str = "local-dev-change-me"
    secrets_encryption_key: str = ""
    discord_guild_id: str = ""
    discord_channel_name_template: str = "{project_name}"
    discord_channel_category_id: str = ""
    voice_stt_provider: Literal["disabled", "openai", "whisper"] = "disabled"
    voice_tts_provider: Literal["disabled", "pocket_tts"] = "disabled"
    voice_transcription_model: str = "gpt-4o-mini-transcribe"
    voice_transcription_language: str = ""
    voice_transcription_openai_api_key: str = ""
    voice_transcription_device: str = "auto"
    voice_transcription_compute_type: str = "int8"
    voice_attachment_max_bytes: int = 25000000
    pocket_tts_base_url: str = ""
    pocket_tts_voice: str = ""
    discord_live_voice_transport_command: str = "/usr/local/bin/live-voice-transport"
    discord_live_voice_transport_startup_timeout_seconds: int = 10
    discord_live_voice_transport_request_timeout_seconds: int = 10
    codex_cli_command: str = "codex"
    codex_sandbox_mode: str = "workspace-write"
    codex_supported_models: str = "gpt-5.4,gpt-5.5,gpt-5.4-mini,gpt-5.3-codex"
    chat_cli_command: str = ""
    claude_cli_command: str = ""
    chat_model: str = "gpt-5.4"
    chat_reasoning_effort: Literal["low", "medium", "high"] = "medium"
    codex_tool_database_url: str = ""
    codex_reasoning_effort: Literal["low", "medium", "high"] = "medium"
    codex_stderr_log_mode: Literal["all", "errors_only", "off"] = "errors_only"
    codex_db_log_sampling_interval: int = 100
    codex_persist_turn_completed_usage: bool = True
    codex_raw_log_path: str = "/tmp/orchestrator-codex.ndjson"
    codex_max_output_tokens: int = 1800
    codex_hang_detection_quiet_seconds: int = 300
    codex_hang_detection_report_interval_seconds: int = 120
    runtime_log_batch_size: int = 50
    runtime_log_batch_flush_ms: int = 50
    log_db_batch_size: int = 200
    log_db_batch_flush_ms: int = 50
    log_retention_sweep_seconds: int = 60
    clickhouse_http_url: str = "http://127.0.0.1:8123"
    clickhouse_database: str = "master_builder"
    clickhouse_username: str = "master_builder"
    clickhouse_password: str = "master_builder"
    clickhouse_query_timeout_seconds: int = 30
    event_stream_poll_ms: int = 500
    knowledge_injection_enabled: bool = True
    knowledge_base_enabled_default: bool = True
    knowledge_auto_answer_mode_default: Literal["safe", "balanced", "aggressive"] = "aggressive"
    knowledge_context_top_k: int = 5
    knowledge_context_max_chars: int = 3200
    knowledge_embedding_model: str = "BAAI/bge-small-en-v1.5"
    knowledge_jira_auto_sync_enabled: bool = True
    knowledge_jira_sync_interval_seconds: int = 3600
    knowledge_jira_sync_poll_seconds: int = 30
    knowledge_jira_sync_lock_key: int = 947102033128
    knowledge_jira_sync_max_issues: int = 500
    knowledge_jira_sync_invalid_token_backoff_seconds: int = 21600
    jira_project_reconciliation_interval_seconds: int = 1800
    jira_project_reconciliation_poll_seconds: int = 30
    jira_project_reconciliation_lock_key: int = 947102033132
    jira_project_reconciliation_max_items: int = 1000
    stage_spi_enabled: bool = False
    stage_spi_default_plugin: str = "design"
    stage_spi_llm_planning_enabled: bool = False
    project_automation_lock_key: int = 947102033131
    project_automation_poll_seconds: int = 30
    project_automation_interval_seconds: int = 30
    workflow_orchestrated_run_timeout_minutes: int = 90
    orchestration_backend: Literal["legacy", "temporal"] = "legacy"
    temporal_target_host: str = "127.0.0.1:7233"
    temporal_namespace: str = "default"
    temporal_task_queue: str = "master-builder"
    otel_enabled: bool = False
    otel_service_namespace: str = "master-builder"
    otel_exporter_otlp_endpoint: str = ""
    otel_exporter_otlp_headers: str = ""
    otel_traces_sample_ratio: float = 1.0
    run_events_initial_limit: int = 100
    logging_pane_initial_log_limit: int = 200
    project_repo_checkout_base_dir: str = "/tmp/master-builder-project-repos"
    runtime_home: str = ""
    worker_poll_interval_seconds: int = 5
    worker_run_heartbeat_interval_seconds: int = 30
    worker_run_stale_timeout_seconds: int = 300
    workflow_operation_attempt_heartbeat_interval_seconds: int = 30
    workflow_operation_attempt_stale_timeout_seconds: int = 300
    worker_stale_sweep_interval_seconds: int = 60
    worker_max_child_processes: int = 5
    worker_runtime_readiness_refresh_seconds: int = 30
    worker_runtime_auth_remediation_ttl_seconds: int = 900
    tenant_archive_retention_days: int = 60
    tenant_archive_sweep_interval_seconds: int = 3600
    discord_gateway_lock_key: int = 947102033127
    discord_gateway_poll_seconds: int = 3
    discord_live_voice_lock_key: int = 947102033129
    discord_live_voice_poll_seconds: int = 3
    auto_migrate_on_startup: bool = True
    sentry_dsn: str = ""
    sentry_environment: str = "dev"
    sentry_release: str = ""
    sentry_traces_sample_rate: float = 0.0
    agent_id: str = "worker-linux-local"
    worker_capabilities: str = "linux"
    worker_runtime_kinds: str = "codex_cli"
    worker_workspace_key: str = ""
    discord_command_sync_lock_key: int = 947102033130

    model_config = SettingsConfigDict(
        env_prefix="ORCHESTRATOR_",
        extra="ignore",
    )


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()
