from __future__ import annotations

from orchestrator.core.worker.run_dispatch_gateways import RunDispatchIdentityGateway
from orchestrator.core.worker.run_dispatch_gateways import RunDispatchStatusConfig
from orchestrator.core.worker.run_dispatch_gateways import RunExecutionGateway
from orchestrator.core.worker.run_dispatch_gateways import RunProjectGateway
from orchestrator.core.worker.run_dispatch_gateways import RunStageUpdateGateway
from orchestrator.core.worker.capabilities import resolve_worker_capability_context
from orchestrator.core.worker.run_dispatch_workflow import (
    RunDispatchWorkflow,
    RunDispatchWorkflowDeps,
)


def process_next_queued_run(
    *,
    session,
    runner,
    logger,
    settings_fn,
    claim_next_queued_run_fn,
    send_discord_message_fn,
    send_jira_message_fn,
    resolve_project_for_run_fn,
    fail_missing_project_mapping_fn,
    block_archived_project_fn,
    ensure_project_repository_checkout_fn,
    fail_project_repository_checkout_fn,
    fail_project_repository_setup_fn,
    cleanup_run_workspaces_fn,
    build_run_heartbeat_controller_fn,
    promote_run_to_running_fn,
    bind_run_project_fn,
    workflow_request_for_run_fn,
    fail_guardrail_violation_fn,
    tenant_jira_issue_url_fn,
    lock_acquired_update_fn,
    repo_setup_ready_update_fn=None,
    plan_posted_update_fn=None,
    pr_opened_update_fn=None,
    run_failed_update_fn=None,
    run_requeued_repo_setup_update_fn=None,
    run_requeued_capability_update_fn=None,
    run_requeued_stale_snapshot_update_fn=None,
    finalize_cancelled_run_fn,
    finalize_workflow_result_fn,
    persist_stage_checkpoint_fn,
    requeue_run_for_repo_setup_fn,
    requeue_workflow_result_for_capability_fn,
    requeue_workflow_result_for_stale_snapshot_fn,
    check_run_snapshot_freshness_fn,
    transition_issue_status_fn=None,
    emit_agent_event_fn,
    resolve_agent_id_fn,
    resolve_worker_service_instance_id_fn,
    run_status_queued: str = "queued",
    run_status_running: str = "running",
    run_status_failed: str = "failed",
    run_status_blocked: str = "blocked",
    run_status_cancelled: str = "cancelled",
    run_status_dispatching: str = "dispatching",
):  # noqa: ANN001
    settings = settings_fn()
    try:
        capability_context = resolve_worker_capability_context(
            raw_value=getattr(settings, "worker_capabilities", ""),
            source="ORCHESTRATOR_WORKER_CAPABILITIES",
        )
    except ValueError:
        raise
    selection = claim_next_queued_run_fn(
        session,
        queued_status=run_status_queued,
        running_status=run_status_running,
        failed_status=run_status_failed,
        worker_service_instance_id=resolve_worker_service_instance_id_fn(),
        worker_capabilities=set(capability_context.available),
        ready_runtime_kinds=getattr(settings, "worker_runtime_kinds", ""),
        running_stale_timeout_seconds=max(
            60,
            int(getattr(settings, "worker_run_stale_timeout_seconds", 300)),
        ),
    )
    return process_claimed_run(
        session=session,
        runner=runner,
        logger=logger,
        settings=settings,
        selection=selection,
        send_discord_message_fn=send_discord_message_fn,
        send_jira_message_fn=send_jira_message_fn,
        resolve_project_for_run_fn=resolve_project_for_run_fn,
        fail_missing_project_mapping_fn=fail_missing_project_mapping_fn,
        block_archived_project_fn=block_archived_project_fn,
        ensure_project_repository_checkout_fn=ensure_project_repository_checkout_fn,
        fail_project_repository_checkout_fn=fail_project_repository_checkout_fn,
        fail_project_repository_setup_fn=fail_project_repository_setup_fn,
        cleanup_run_workspaces_fn=cleanup_run_workspaces_fn,
        build_run_heartbeat_controller_fn=build_run_heartbeat_controller_fn,
        promote_run_to_running_fn=promote_run_to_running_fn,
        bind_run_project_fn=bind_run_project_fn,
        workflow_request_for_run_fn=workflow_request_for_run_fn,
        fail_guardrail_violation_fn=fail_guardrail_violation_fn,
        tenant_jira_issue_url_fn=tenant_jira_issue_url_fn,
        lock_acquired_update_fn=lock_acquired_update_fn,
        repo_setup_ready_update_fn=repo_setup_ready_update_fn,
        plan_posted_update_fn=plan_posted_update_fn,
        pr_opened_update_fn=pr_opened_update_fn,
        run_failed_update_fn=run_failed_update_fn,
        run_requeued_repo_setup_update_fn=run_requeued_repo_setup_update_fn,
        run_requeued_capability_update_fn=run_requeued_capability_update_fn,
        run_requeued_stale_snapshot_update_fn=run_requeued_stale_snapshot_update_fn,
        finalize_cancelled_run_fn=finalize_cancelled_run_fn,
        finalize_workflow_result_fn=finalize_workflow_result_fn,
        persist_stage_checkpoint_fn=persist_stage_checkpoint_fn,
        requeue_run_for_repo_setup_fn=requeue_run_for_repo_setup_fn,
        requeue_workflow_result_for_capability_fn=requeue_workflow_result_for_capability_fn,
        requeue_workflow_result_for_stale_snapshot_fn=requeue_workflow_result_for_stale_snapshot_fn,
        check_run_snapshot_freshness_fn=check_run_snapshot_freshness_fn,
        transition_issue_status_fn=transition_issue_status_fn,
        emit_agent_event_fn=emit_agent_event_fn,
        resolve_agent_id_fn=resolve_agent_id_fn,
        resolve_worker_service_instance_id_fn=resolve_worker_service_instance_id_fn,
        run_status_running=run_status_running,
        run_status_failed=run_status_failed,
        run_status_blocked=run_status_blocked,
        run_status_cancelled=run_status_cancelled,
        run_status_dispatching=run_status_dispatching,
    )


def process_claimed_run(
    *,
    session,
    runner,
    logger,
    settings,
    selection,
    send_discord_message_fn,
    send_jira_message_fn,
    resolve_project_for_run_fn,
    fail_missing_project_mapping_fn,
    block_archived_project_fn,
    ensure_project_repository_checkout_fn,
    fail_project_repository_checkout_fn,
    fail_project_repository_setup_fn,
    cleanup_run_workspaces_fn,
    build_run_heartbeat_controller_fn,
    promote_run_to_running_fn,
    bind_run_project_fn,
    workflow_request_for_run_fn,
    fail_guardrail_violation_fn,
    tenant_jira_issue_url_fn,
    lock_acquired_update_fn,
    repo_setup_ready_update_fn=None,
    plan_posted_update_fn=None,
    pr_opened_update_fn=None,
    run_failed_update_fn=None,
    run_requeued_repo_setup_update_fn=None,
    run_requeued_capability_update_fn=None,
    run_requeued_stale_snapshot_update_fn=None,
    finalize_cancelled_run_fn,
    finalize_workflow_result_fn,
    persist_stage_checkpoint_fn,
    requeue_run_for_repo_setup_fn,
    requeue_workflow_result_for_capability_fn,
    requeue_workflow_result_for_stale_snapshot_fn,
    check_run_snapshot_freshness_fn,
    transition_issue_status_fn=None,
    emit_agent_event_fn,
    resolve_agent_id_fn,
    resolve_worker_service_instance_id_fn,
    run_status_running: str = "running",
    run_status_failed: str = "failed",
    run_status_blocked: str = "blocked",
    run_status_cancelled: str = "cancelled",
    run_status_dispatching: str = "dispatching",
):  # noqa: ANN001
    statuses = RunDispatchStatusConfig(
        running=run_status_running,
        failed=run_status_failed,
        blocked=run_status_blocked,
        cancelled=run_status_cancelled,
        dispatching=run_status_dispatching,
    )
    deps = RunDispatchWorkflowDeps(
        identity=RunDispatchIdentityGateway(
            logger=logger,
            cleanup_run_workspaces_fn=cleanup_run_workspaces_fn,
            build_run_heartbeat_controller_fn=build_run_heartbeat_controller_fn,
            emit_agent_event_fn=emit_agent_event_fn,
            resolve_agent_id_fn=resolve_agent_id_fn,
            resolve_worker_service_instance_id_fn=resolve_worker_service_instance_id_fn,
        ),
        project=RunProjectGateway(
            resolve_project_for_run_fn=resolve_project_for_run_fn,
            fail_missing_project_mapping_fn=fail_missing_project_mapping_fn,
            block_archived_project_fn=block_archived_project_fn,
            bind_run_project_fn=bind_run_project_fn,
            tenant_jira_issue_url_fn=tenant_jira_issue_url_fn,
            transition_issue_status_fn=transition_issue_status_fn,
        ),
        stage_updates=RunStageUpdateGateway(
            send_discord_message_fn=send_discord_message_fn,
            send_jira_message_fn=send_jira_message_fn,
            lock_acquired_update_fn=lock_acquired_update_fn,
            repo_setup_ready_update_fn=repo_setup_ready_update_fn,
            plan_posted_update_fn=plan_posted_update_fn,
            pr_opened_update_fn=pr_opened_update_fn,
            run_failed_update_fn=run_failed_update_fn,
            run_requeued_repo_setup_update_fn=run_requeued_repo_setup_update_fn,
            run_requeued_capability_update_fn=run_requeued_capability_update_fn,
            run_requeued_stale_snapshot_update_fn=run_requeued_stale_snapshot_update_fn,
        ),
        execution=RunExecutionGateway(
            promote_run_to_running_fn=promote_run_to_running_fn,
            workflow_request_for_run_fn=workflow_request_for_run_fn,
            fail_guardrail_violation_fn=fail_guardrail_violation_fn,
            ensure_project_repository_checkout_fn=ensure_project_repository_checkout_fn,
            fail_project_repository_checkout_fn=fail_project_repository_checkout_fn,
            fail_project_repository_setup_fn=fail_project_repository_setup_fn,
            finalize_cancelled_run_fn=finalize_cancelled_run_fn,
            finalize_workflow_result_fn=finalize_workflow_result_fn,
            persist_stage_checkpoint_fn=persist_stage_checkpoint_fn,
            requeue_run_for_repo_setup_fn=requeue_run_for_repo_setup_fn,
            requeue_workflow_result_for_capability_fn=requeue_workflow_result_for_capability_fn,
            requeue_workflow_result_for_stale_snapshot_fn=requeue_workflow_result_for_stale_snapshot_fn,
            check_run_snapshot_freshness_fn=check_run_snapshot_freshness_fn,
        ),
        statuses=statuses,
    )
    return RunDispatchWorkflow(
        session=session,
        runner=runner,
        settings=settings,
        deps=deps,
    ).execute(selection=selection)
