from __future__ import annotations

from datetime import datetime

from orchestrator.storage.models import Run, WorkflowExecution


def build_workflow_execution_for_attempt(
    *,
    workflow_id: str,
    workflow_type_key: str,
    tenant_id: str,
    project_id: str | None,
    source_system: str,
    source_ref: str,
    display_name: str | None,
    source_description: str | None,
    repo_url: str | None,
    branch: str | None,
    pr_url: str | None,
    orchestration_backend: str,
    dedupe_scope: str,
    status: str,
    created_at: datetime,
    updated_at: datetime,
    active_run_id: str | None = None,
    latest_checkpoint_id: str | None = None,
    source_workflow_id: str | None = None,
    source_run_id: str | None = None,
    started_at: datetime | None = None,
    finished_at: datetime | None = None,
    last_error: str | None = None,
) -> WorkflowExecution:
    return WorkflowExecution(
        workflow_id=workflow_id,
        workflow_type_key=workflow_type_key,
        tenant_id=tenant_id,
        project_id=project_id,
        source_system=source_system,
        source_ref=source_ref,
        display_name=display_name,
        source_description=source_description,
        repo_url=repo_url,
        branch=branch,
        pr_url=pr_url,
        orchestration_backend=orchestration_backend,
        dedupe_scope=dedupe_scope,
        status=status,
        last_error=last_error,
        active_run_id=active_run_id,
        latest_checkpoint_id=latest_checkpoint_id,
        source_workflow_id=source_workflow_id,
        source_run_id=source_run_id,
        created_at=created_at,
        started_at=started_at,
        finished_at=finished_at,
        updated_at=updated_at,
    )


def build_run_attempt(
    *,
    run_id: str,
    workflow_id: str,
    tenant_id: str,
    project_id: str | None,
    issue_key: str,
    issue_summary: str | None,
    issue_description: str | None,
    repo_url: str | None,
    branch: str | None,
    pr_url: str | None,
    attempt_number: int,
    parent_run_id: str | None,
    entry_mode: str,
    entry_stage: str | None,
    entry_checkpoint_id: str | None,
    dedupe_scope: str,
    plan: dict[str, object] | None,
    status: str,
    pre_check_outcome: str | None,
    required_worker_capability: str | None,
    required_runtime_kinds_json: list[str] | None,
    created_at: datetime,
    dispatch_claimed_at: datetime | None = None,
    started_at: datetime | None = None,
    last_heartbeat_at: datetime | None = None,
    worker_service_instance_id: str | None = None,
    finished_at: datetime | None = None,
    last_error: str | None = None,
    claim_id: str | None = None,
) -> Run:
    return Run(
        run_id=run_id,
        workflow_id=workflow_id,
        tenant_id=tenant_id,
        project_id=project_id,
        issue_key=issue_key,
        issue_summary=issue_summary,
        issue_description=issue_description,
        repo_url=repo_url,
        branch=branch,
        pr_url=pr_url,
        attempt_number=attempt_number,
        parent_run_id=parent_run_id,
        entry_mode=entry_mode,
        entry_stage=entry_stage,
        entry_checkpoint_id=entry_checkpoint_id,
        dedupe_scope=dedupe_scope,
        plan=plan,
        status=status,
        last_error=last_error,
        pre_check_outcome=pre_check_outcome,
        required_worker_capability=required_worker_capability,
        required_runtime_kinds_json=required_runtime_kinds_json,
        claim_id=claim_id,
        created_at=created_at,
        dispatch_claimed_at=dispatch_claimed_at,
        started_at=started_at,
        last_heartbeat_at=last_heartbeat_at,
        worker_service_instance_id=worker_service_instance_id,
        finished_at=finished_at,
    )
