from __future__ import annotations

import base64
import os
import re
import subprocess
from pathlib import Path

DEPLOYMENT_COMPOSE_ARTIFACT_PATH = ".master-builder/deployments/docker-compose.yml"
COOLIFY_RUNTIME_ENV_ARTIFACT_PATH = ".env"
COOLIFY_RUNTIME_ENV_ARTIFACT = "# Generated by Master Builder. Runtime values are managed by Coolify.\n"


def git_auth_env(token: str) -> dict[str, str]:
    credential = base64.b64encode(f"x-access-token:{token}".encode("utf-8")).decode("ascii")
    return {
        **os.environ,
        "GIT_CONFIG_COUNT": "1",
        "GIT_CONFIG_KEY_0": "http.https://github.com/.extraheader",
        "GIT_CONFIG_VALUE_0": f"AUTHORIZATION: basic {credential}",
    }


def run_git(args: list[str], *, cwd: Path, token: str | None = None) -> str:
    process = subprocess.run(
        ["git", *args],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=False,
        env=git_auth_env(token) if token else None,
    )
    if process.returncode != 0:
        message = (process.stderr or process.stdout or "git command failed").strip()
        raise RuntimeError(message)
    return process.stdout


def run_command(args: list[str], *, cwd: Path) -> str:
    process = subprocess.run(
        args,
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=False,
    )
    if process.returncode != 0:
        message = (process.stderr or process.stdout or "command failed").strip()
        raise RuntimeError(message)
    return process.stdout


def checkout_branch_commit(*, repo_dir: Path, branch: str, commit_sha: str) -> None:
    if not (repo_dir / ".git").exists():
        raise RuntimeError(f"Project repository checkout is missing git metadata at {repo_dir}")
    run_git(["checkout", "-B", branch, f"origin/{branch}"], cwd=repo_dir)
    run_git(["reset", "--hard", commit_sha], cwd=repo_dir)


def deployment_branch_name(*, project_id: str, source_branch: str, source_commit_sha: str) -> str:
    project_slug = re.sub(r"[^a-z0-9._-]+", "-", str(project_id or "").lower()).strip("-") or "project"
    branch_slug = re.sub(r"[^a-z0-9._-]+", "-", str(source_branch or "").lower()).strip("-") or "branch"
    commit_slug = re.sub(r"[^a-f0-9]+", "", str(source_commit_sha or "").lower())[:12] or "commit"
    return f"mb/deploy/{project_slug}/{branch_slug}-{commit_slug}"


def resolve_repo_path(*, repo_dir: Path, relative_path: str) -> Path:
    root = repo_dir.resolve()
    resolved = (root / relative_path).resolve()
    try:
        resolved.relative_to(root)
    except ValueError as exc:
        raise RuntimeError(f"Deployment artifact path escapes the repository: {relative_path}") from exc
    return resolved


def sync_npm_lockfiles_for_deployment_branch(
    *,
    repo_dir: Path,
    npm_service_source_paths: tuple[str, ...],
    run_command_fn=run_command,  # noqa: ANN001
) -> tuple[str, ...]:
    changed_lockfiles: set[str] = set()
    for source_path in sorted({str(path or "").strip() for path in npm_service_source_paths if str(path or "").strip()}):
        service_dir = resolve_repo_path(repo_dir=repo_dir, relative_path=source_path)
        package_json = service_dir / "package.json"
        if not package_json.exists():
            raise RuntimeError(f"NPM deployment service at {source_path} is missing package.json")
        run_command_fn(
            ["npm", "install", "--package-lock-only", "--ignore-scripts", "--no-audit", "--no-fund"],
            cwd=service_dir,
        )
        lockfiles = [service_dir / "npm-shrinkwrap.json", service_dir / "package-lock.json"]
        existing_lockfiles = [path for path in lockfiles if path.exists()]
        if not existing_lockfiles:
            raise RuntimeError(f"NPM deployment service at {source_path} did not produce a lockfile")
        for lockfile in existing_lockfiles:
            changed_lockfiles.add(str(lockfile.relative_to(repo_dir.resolve())))
    return tuple(sorted(changed_lockfiles))


def ensure_deployment_compose_artifact(
    *,
    repo_dir: Path,
    project_id: str,
    source_branch: str,
    source_commit_sha: str,
    compose_raw: str,
    npm_service_source_paths: tuple[str, ...],
    token: str,
) -> tuple[str, str, str]:
    artifact_branch = deployment_branch_name(
        project_id=project_id,
        source_branch=source_branch,
        source_commit_sha=source_commit_sha,
    )
    run_git(["fetch", "origin", source_branch], cwd=repo_dir, token=token)
    try:
        run_git(["fetch", "origin", artifact_branch], cwd=repo_dir, token=token)
        run_git(["checkout", "-B", artifact_branch, f"origin/{artifact_branch}"], cwd=repo_dir)
    except RuntimeError:
        run_git(["checkout", "-B", artifact_branch, source_commit_sha], cwd=repo_dir)
    npm_lockfile_paths = sync_npm_lockfiles_for_deployment_branch(
        repo_dir=repo_dir,
        npm_service_source_paths=npm_service_source_paths,
    )
    artifact_path = repo_dir / DEPLOYMENT_COMPOSE_ARTIFACT_PATH
    artifact_path.parent.mkdir(parents=True, exist_ok=True)
    artifact_path.write_text(compose_raw.rstrip() + "\n", encoding="utf-8")
    runtime_env_path = repo_dir / COOLIFY_RUNTIME_ENV_ARTIFACT_PATH
    runtime_env_path.write_text(COOLIFY_RUNTIME_ENV_ARTIFACT, encoding="utf-8")
    run_git(["add", DEPLOYMENT_COMPOSE_ARTIFACT_PATH, *npm_lockfile_paths], cwd=repo_dir)
    run_git(["add", "-f", COOLIFY_RUNTIME_ENV_ARTIFACT_PATH], cwd=repo_dir)
    changed = run_git(["diff", "--cached", "--name-only"], cwd=repo_dir).strip()
    if changed:
        ensure_local_commit_identity(repo_dir=repo_dir)
        run_git(
            ["commit", "-m", f"{project_id}: update deployment compose for {source_branch} {source_commit_sha[:12]}"],
            cwd=repo_dir,
        )
    deployment_commit_sha = run_git(["rev-parse", "HEAD"], cwd=repo_dir).strip()
    run_git(["push", "-u", "origin", f"HEAD:{artifact_branch}"], cwd=repo_dir, token=token)
    return artifact_branch, deployment_commit_sha, DEPLOYMENT_COMPOSE_ARTIFACT_PATH


def ensure_local_commit_identity(*, repo_dir: Path) -> None:
    try:
        user_name = run_git(["config", "--get", "user.name"], cwd=repo_dir).strip()
    except RuntimeError:
        user_name = ""
    try:
        user_email = run_git(["config", "--get", "user.email"], cwd=repo_dir).strip()
    except RuntimeError:
        user_email = ""
    if not user_name:
        run_git(["config", "user.name", "Master Builder Bot"], cwd=repo_dir)
    if not user_email:
        run_git(["config", "user.email", "master-builder-bot@users.noreply.github.com"], cwd=repo_dir)
